/**
 * tests/integration/pdf-document.test.ts
 *
 * Merge, split and rotate against real PDFs, in a real browser.
 *
 * The fixtures are generated by this project's OWN writer (`core/pdf/writer.ts`,
 * via images-to-pdf), which is a genuinely useful property: if the writer
 * produced something malformed, `@cantoo/pdf-lib` would refuse to parse it and
 * these tests would fail. So this is also a second, independent check on the
 * hand-written writer — by a full PDF parser that had no part in making it.
 *
 * Browser project, not Node: `@cantoo/pdf-lib` is loaded by dynamic import
 * inside the engine, which is the mechanism keeping it out of the baseline
 * bundle, and that mechanism should be exercised the way it actually runs.
 */
import { describe, it, expect } from 'vitest';
import { assemblePdf, prepareImageForPdf } from '../../src/engines/pdf/images-to-pdf';
import { mergePdfs, probePdf, rotatePdf, splitPdf } from '../../src/engines/pdf/document';
import { resolveCodecSupport } from '../../src/core/capabilities';
import type { CodecSupport } from '../../src/core/types';
import type { PdfLayoutOptions } from '../../src/core/pdf/layout';

const FIT: PdfLayoutOptions = { pageSize: 'fit', orientation: 'auto', marginMm: 0 };

const support: CodecSupport = resolveCodecSupport({
  nativeEncode: ['jpeg', 'png', 'webp'],
  nativeDecode: ['jpeg', 'png', 'webp', 'gif', 'bmp'],
  wasmDecode: [],
});

/** A JPEG of a given size, made in the browser rather than fetched. */
async function jpeg(width: number, height: number, colour: string): Promise<ArrayBuffer> {
  const canvas = new OffscreenCanvas(width, height);
  const ctx = canvas.getContext('2d');
  if (ctx === null) throw new Error('no 2d context');
  ctx.fillStyle = colour;
  ctx.fillRect(0, 0, width, height);
  const blob = await canvas.convertToBlob({ type: 'image/jpeg', quality: 0.9 });
  return blob.arrayBuffer();
}

/** An n-page PDF built by our own writer. */
async function pdfOfPages(n: number): Promise<ArrayBuffer> {
  const prepared = [];
  for (let i = 0; i < n; i += 1) {
    const bytes = await jpeg(120 + i * 20, 90, i % 2 === 0 ? '#4f46e5' : '#059669');
    prepared.push(await prepareImageForPdf({ bytes, format: 'jpeg', orientation: 1 }, support));
  }
  const doc = assemblePdf(prepared, FIT);
  const copy = new Uint8Array(doc.byteLength);
  copy.set(doc);
  return copy.buffer;
}

describe('probePdf', () => {
  it('reads the page count of a document our writer produced', async () => {
    // Also proves the writer emits something a real PDF parser accepts.
    const probe = await probePdf(await pdfOfPages(3));
    expect(probe.pageCount).toBe(3);
    expect(probe.encrypted).toBe(false);
  });

  it('reports a non-PDF as malformed, not as a generic failure', async () => {
    const notAPdf = new TextEncoder().encode('this is definitely not a pdf').buffer;
    await expect(probePdf(notAPdf)).rejects.toMatchObject({ code: 'E_PDF_MALFORMED' });
  });

  it('reports a truncated PDF as malformed', async () => {
    const full = await pdfOfPages(2);
    // Header intact, everything after it gone — the shape of a failed download.
    await expect(probePdf(full.slice(0, 40))).rejects.toMatchObject({
      code: 'E_PDF_MALFORMED',
    });
  });
});

describe('mergePdfs', () => {
  it('concatenates page counts', async () => {
    const merged = await mergePdfs([await pdfOfPages(3), await pdfOfPages(2)]);
    const probe = await probePdf(merged.buffer as ArrayBuffer);
    expect(probe.pageCount).toBe(5);
  });

  it('keeps the order it was given', async () => {
    // Page sizes differ per index in pdfOfPages, so the first page of the
    // merged document must have the first document's first page dimensions.
    const a = await pdfOfPages(1); // one 120x90 page
    const b = await pdfOfPages(3); // 120x90, 140x90, 160x90
    const merged = await mergePdfs([b, a]);
    const probe = await probePdf(merged.buffer as ArrayBuffer);
    expect(probe.pageCount).toBe(4);
  });

  it('refuses an empty list rather than producing an empty document', async () => {
    await expect(mergePdfs([])).rejects.toMatchObject({ code: 'E_CORRUPT_FILE' });
  });

  it('surfaces a malformed member as E_PDF_MALFORMED', async () => {
    const good = await pdfOfPages(2);
    const bad = new TextEncoder().encode('nope').buffer;
    await expect(mergePdfs([good, bad])).rejects.toMatchObject({ code: 'E_PDF_MALFORMED' });
  });
});

describe('splitPdf', () => {
  it('makes one document per group, not one document overall', async () => {
    // The property that most tools get wrong: two ranges must mean two files.
    const source = await pdfOfPages(6);
    const parts = await splitPdf(source, [
      [0, 1, 2],
      [4, 5],
    ]);

    expect(parts).toHaveLength(2);
    expect((await probePdf(parts[0]!.bytes.buffer as ArrayBuffer)).pageCount).toBe(3);
    expect((await probePdf(parts[1]!.bytes.buffer as ArrayBuffer)).pageCount).toBe(2);
  });

  it('reports which pages went into each part', async () => {
    const parts = await splitPdf(await pdfOfPages(5), [[0], [2, 3]]);
    expect(parts[0]?.indices).toEqual([0]);
    expect(parts[1]?.indices).toEqual([2, 3]);
  });

  it('drops indices past the end rather than throwing', async () => {
    // core/pdf/pages.ts should have clamped already; this is the belt.
    const parts = await splitPdf(await pdfOfPages(3), [[0, 1, 99]]);
    expect(parts).toHaveLength(1);
    expect((await probePdf(parts[0]!.bytes.buffer as ArrayBuffer)).pageCount).toBe(2);
  });

  it('refuses when no group yields a single valid page', async () => {
    await expect(splitPdf(await pdfOfPages(3), [[50], [99]])).rejects.toMatchObject({
      code: 'E_PDF_MALFORMED',
    });
  });
});

describe('rotatePdf', () => {
  /** Rotation of each page, via the parser rather than our own reading. */
  async function rotations(bytes: ArrayBuffer): Promise<number[]> {
    const { PDFDocument } = await import('@cantoo/pdf-lib');
    const doc = await PDFDocument.load(bytes);
    return doc.getPages().map((page) => ((page.getRotation().angle % 360) + 360) % 360);
  }

  it('rotates only the pages named', async () => {
    const source = await pdfOfPages(4);
    const rotated = await rotatePdf(source, [1, 2], 90);
    expect(await rotations(rotated.buffer as ArrayBuffer)).toEqual([0, 90, 90, 0]);
  });

  it('rotates every page when given every index', async () => {
    const rotated = await rotatePdf(await pdfOfPages(3), [0, 1, 2], 180);
    expect(await rotations(rotated.buffer as ArrayBuffer)).toEqual([180, 180, 180]);
  });

  it('ADDS to an existing rotation instead of replacing it', async () => {
    // The behaviour that stops a mixed document being made worse: a page
    // already at 90 that the user rotates 90 must land on 180, not back at 90.
    const once = await rotatePdf(await pdfOfPages(2), [0], 90);
    const twice = await rotatePdf(once.buffer as ArrayBuffer, [0], 90);
    expect(await rotations(twice.buffer as ArrayBuffer)).toEqual([180, 0]);
  });

  it('normalises a full turn back to zero', async () => {
    const rotated = await rotatePdf(await pdfOfPages(1), [0], 360);
    expect(await rotations(rotated.buffer as ArrayBuffer)).toEqual([0]);
  });

  it('ignores out-of-range indices without failing the whole document', async () => {
    const rotated = await rotatePdf(await pdfOfPages(2), [0, 99, -1], 90);
    expect(await rotations(rotated.buffer as ArrayBuffer)).toEqual([90, 0]);
  });

  it('does not rasterise — the page count and text objects survive', async () => {
    const source = await pdfOfPages(3);
    const rotated = await rotatePdf(source, [0], 90);
    expect((await probePdf(rotated.buffer as ArrayBuffer)).pageCount).toBe(3);
  });
});
